### ISSUE TITLE
Leave-One-Subject-Out cross validation

### ISSUE THREAD

**Issue by 13293824182** [IcedDoggie/Micro-Expression-with-Deep-Learning#17]
Can you tell me the details of this method (Leave-One-Subject-Out cross validation) ?

**Comment by 13293824182** [comment]
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    main(args)
  File "main.py", line 15, in main
    train(args.batch_size, args.spatial_epochs, args.temporal_epochs, args.train_id, args.dB, args.spatial_size, args.flag, args.obj                              ective_flag, args.tensorboard)
  File "/home/lhh/TensorFlow/Micro-Expression-with-Deep-Learning/train.py", line 262, in train
    vgg_model = VGG_16(spatial_size = spatial_size, classes=n_exp, channels=3, weights_path='VGG_Face_Deep_16.h5')
  File "/home/lhh/TensorFlow/Micro-Expression-with-Deep-Learning/models.py", line 139, in VGG_16
    model.load_weights(weights_path)
  File "/home/lhh/.pythonlib/lib/python3.5/site-packages/keras/models.py", line 720, in load_weights
    topology.load_weights_from_hdf5_group(f, layers)
  File "/home/lhh/.pythonlib/lib/python3.5/site-packages/keras/engine/topology.py", line 3048, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/lhh/.pythonlib/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2183, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/home/lhh/anaconda3/envs/dv/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 573, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/home/lhh/anaconda3/envs/dv/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "/home/lhh/anaconda3/envs/dv/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 57, in assign
    use_locking=use_locking, name=name)
  File "/home/lhh/anaconda3/envs/dv/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_                              op_helper
    op_def=op_def)
  File "/home/lhh/anaconda3/envs/dv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/home/lhh/anaconda3/envs/dv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_ou                              tputs
    shapes = shape_func(op)
  File "/home/lhh/anaconda3/envs/dv/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiri                              ng
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/lhh/anaconda3/envs/dv/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp                              _shape_fn
    require_shape_fn)
  File "/home/lhh/anaconda3/envs/dv/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cp                              p_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 1 in both shapes must be equal, but are 2622 and 1000 for 'Assign_30' (op: 'Assign') with input shapes: [4096, 2622], [4096,1000].
i  get the error , and How to solve this problem
